export const ADD_STUDENT = 'ADD_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const TOGGLE_STUDENT_FORM = 'TOGGLE_STUDENT_FORM';
export const TOGGLE_TRANSACTION_FORM = 'TOGGLE_TRANSACTION_FORM';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';